# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Readonly-XS
version:      1.04
version_from: XS.pm
installdirs:  site
requires:
    Readonly:                      1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
