# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Output
version:      0.10
version_from: lib/Test/Output.pm
installdirs:  site
requires:
    Sub::Exporter:                 0
    Test::More:                    0
    Test::Tester:                  0.103

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
