# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-MockTime
version:      0.04
version_from: lib/Test/MockTime.pm
installdirs:  site
requires:
    Test::More:                    0
    Time::Local:                   0
    Time::Piece:                   1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
