# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-File
version:      1.16
version_from: lib/File.pm
installdirs:  site
requires:
    Test::Builder:                 0.32
    Test::Builder::Tester:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
