# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-MockModule
version:      0.05
version_from: lib/Test/MockModule.pm
installdirs:  site
requires:
    Scalar::Util:                  0
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
