#!/bin/bash

#DEBHELPER#

case "$1" in
	configure)
		kill `pidof gconfd-2` >/dev/null 2>&1 || true

		# restart mail to generate configuration files
		invoke-rc.d ebox mail restart

		# restart saslauthdaemon
		invoke-rc.d saslauthd restart

		# create log table
		/usr/share/ebox/ebox-sql-table add message /usr/share/ebox/sqllog/mail.sql

        # restart logs
        invoke-rc.d ebox logs restart || true

        # restart apache
        invoke-rc.d ebox apache restart || true
esac



exit 0
