# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-NoWarnings
version:      0.082
version_from: ./lib/Test/NoWarnings.pm
installdirs:  perl
requires:
    Test::Tester:                  0.103

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
