#!/bin/bash

#DEBHELPER#

onInstall() {
    perl -e 'use EBox::Printers; EBox::Printers::onInstall();'
} 


case "$1" in
    configure)
        kill `pidof gconfd-2` >/dev/null 2>&1 || true
        
        # add ebox to lpdadmin to manage printers and queues
        adduser --quiet ebox lpadmin

        # add ebox to lp to read cups logs
        adduser --quiet ebox lp

        onInstall

        # Restart eBox apache
        invoke-rc.d ebox apache restart || true

     ;;
esac



exit 0
