#!/bin/bash

#DEBHELPER#

case "$1" in
	configure)

        kill `pidof gconfd-2` >/dev/null 2>&1 || true

       # migrate data if needed
       /usr/share/ebox/ebox-migrate /usr/share/ebox-antivirus/migration/

       # Undo clamd modification done by previous packages
       APP_PROFILE="/etc/apparmor.d/usr.sbin.clamd"
       if [ -f $APP_PROFILE ]; then
           sed -i 's:^/usr/sbin/clamd.off.*:/usr/sbin/clamd {:' $APP_PROFILE || true
           /etc/init.d/apparmor restart || true
       fi


       # create directory for freshclam data
        FRESHCLAM_DIR=$(perl -MEBox::AntiVirus -e'print EBox::AntiVirus::freshclamEBoxDir();   1;'); 
        mkdir -p $FRESHCLAM_DIR
        chown clamav.clamav $FRESHCLAM_DIR

        # restart logs
        invoke-rc.d ebox logs restart || true

        # restart module
        invoke-rc.d ebox antivirus restart

        invoke-rc.d ebox apache restart || true
esac



exit 0


