#!/usr/bin/perl

use strict;
use warnings;

use EBox::Global;

my $global = EBox::Global->modInstance('global');

sub usage {
	print "Usage: $0 start|stop|restart\n";
	exit 1;
}

sub start() {
	my @names = $global->modNames;
	foreach (@names) {
		my $mod = EBox::Global->modInstance($_);
		print "EBox: starting $_ ";
		$mod->restartService;
		print ".\n";
	}
}

sub stop() {
	my @names = $global->modNames;
	foreach (@names) {
		my $mod = EBox::Global->modInstance($_);
		print "EBox: stopping $_ ";
		$mod->stopService;
		print ".\n";
	}
}

if (@ARGV != 1) {
	usage;
}


if ($ARGV[0] eq "start") {
	start();
} elsif ($ARGV[0] eq "restart") {
	stop();
	start();
} elsif ($ARGV[0] eq "stop") {
	stop();
} else {
	usage;
}
